import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>

        <title>SportSee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" /> 

      </Head>

      <main className={styles.main}>
        <Image 
              src="/logos/logo_main.png"
              alt="sportsee logo"
              height={122} // Desired size with correct aspect ratio
              width={356} // Desired size with correct aspect ratio
          />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image 
            src="/logos/logo_main.png"
            alt="sportsee logo"
            height={30.5} // Desired size with correct aspect ratio
            width={89} // Desired size with correct aspect ratio
            />
        </a>
      </footer>
    </div>
  )
}
